#include_recipe "pivotal_workstation::postgres"
include_recipe "tm-osx-apps::postgres_app"
include_recipe "pivotal_workstation::redis"
include_recipe "pivotal_workstation::memcached"
include_recipe "sprout-osx-apps::imagemagick"
#include_recipe "sprout-osx-apps::ffmpeg"
include_recipe "sprout-osx-apps::node_js"
include_recipe "tm::mysql"
